name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: my-fastapi-rg
  AZURE_APP_NAME: fastapi-app
  AZURE_LOCATION: eastus
  POSTGRES_ADMIN: myadmin
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep
      run: |
        az deployment group create \
          --resource-group $AZURE_RESOURCE_GROUP \
          --template-file infrastructure/main.bicep \
          --parameters appName=$AZURE_APP_NAME \
                       postgresAdmin=$POSTGRES_ADMIN \
                       postgresPassword=$POSTGRES_PASSWORD

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_APP_NAME }}
        package: .
